### ISSUE TITLE
Testing With Datetime Deltas

### ISSUE THREAD

**Issue by ngottlieb** [pat/ts-datetime-delta#17]
Do you have any recommendations for how to handle testing that relies on the delta index in this implementation? I can always just re-index completely after creating objects, but the stock delta implementation made this much easier as the delta indices were appropriately processed every time I created a new object with FactoryGirl, so switching is breaking a bunch of my tests and I wonder if there's a better way to do this besides just adding index calls everywhere it's needed.

**Comment by ngottlieb** [comment]
I guess there may not be a good way to deal with this. You could potentially have testing run with real-time delta processing somehow (stock implementation) while production runs with the timestamps.

**Comment by pat** [comment]
Hi Nick

Sorry for a complete lack of a speedy reply. I can't think of a way of handling this without any index calls, but it's worth noting that `ThinkingSphinx::Test.index` does accept arguments of index names… so you could use `ThinkingSphinx::Test.index 'article_delta'` and thus only process the delta index (faster and a more accurate representation).

Still, that still requires you modifying your tests accordingly. Not ideal, but I've not thought of anything else at this point.
